"""STIX loading routes."""

from typing import Dict, Any
from fastapi import APIRouter, HTTPException, Query, Body, Request
from bandjacks.services.api.settings import settings
from bandjacks.services.api.schemas import UpsertResult
from bandjacks.services.api.middleware import get_trace_id
from bandjacks.loaders.attack_upsert import resolve_bundle, fetch_bundle, adm_validate, upsert_to_graph_and_vectors
from bandjacks.loaders.provenance import make_provenance
import uuid
from datetime import datetime
from neo4j import GraphDatabase

router = APIRouter(tags=["stix"])


def _get_current_version(collection: str) -> str | None:
    """Get the current version of a collection from the database."""
    driver = GraphDatabase.driver(
        settings.neo4j_uri,
        auth=(settings.neo4j_user, settings.neo4j_password)
    )
    
    try:
        with driver.session() as session:
            result = session.run(
                """
                MATCH (n)
                WHERE n.source_collection = $collection
                AND n.source_version IS NOT NULL
                WITH n.source_version as version, MAX(n.modified) as max_modified
                RETURN version
                ORDER BY max_modified DESC
                LIMIT 1
                """,
                collection=collection
            )
            record = result.single()
            return record["version"] if record else None
    finally:
        driver.close()


def _is_downgrade(current_version: str, new_version: str) -> bool:
    """Check if new_version is older than current_version."""
    try:
        # Parse version numbers (e.g., "14.1" -> (14, 1))
        current_parts = tuple(int(x) for x in current_version.split('.'))
        new_parts = tuple(int(x) for x in new_version.split('.'))
        return new_parts < current_parts
    except (ValueError, AttributeError):
        # If we can't parse, be conservative and allow
        return False

@router.post("/stix/load/attack", response_model=UpsertResult)
async def load_attack_collection(
    request: Request,
    collection: str = Query(..., pattern="^(enterprise-attack|mobile-attack|ics-attack)$"),
    version: str | None = Query(None, description="e.g., 17.1 or 'latest'"),
    adm_strict: bool = Query(True),
    force: bool = Query(False, description="Force load even if version is older"),
):
    try:
        url, resolved_version, modified = resolve_bundle(settings.attack_index_url, collection, version)
        
        # Check for version downgrade
        if not force:
            current_version = _get_current_version(collection)
            if current_version and _is_downgrade(current_version, resolved_version):
                raise HTTPException(
                    status_code=409,
                    detail=f"Version downgrade detected: current={current_version}, requested={resolved_version}. Use force=true to override."
                )
        
        bundle = fetch_bundle(url)

        ok, rejected, adm_sha = adm_validate(bundle, adm_strict, settings.adm_mode, settings.adm_spec_min)
        if not ok and adm_strict:
            return UpsertResult(
                inserted=0, updated=0, rejected=rejected,
                provenance=make_provenance(collection, resolved_version, modified, url, settings.adm_spec_min, adm_sha),
                trace_id=getattr(request.state, 'trace_id', None)
            )

        inserted, updated = upsert_to_graph_and_vectors(
            bundle=bundle, collection=collection, version=resolved_version,
            neo4j_uri=settings.neo4j_uri, neo4j_user=settings.neo4j_user, neo4j_password=settings.neo4j_password,
            os_url=settings.opensearch_url, os_index=settings.os_index_nodes
        )

        return UpsertResult(
            inserted=inserted, updated=updated, rejected=rejected,
            provenance=make_provenance(collection, resolved_version, modified, url, settings.adm_spec_min, adm_sha),
            trace_id=getattr(request.state, 'trace_id', None)
        )
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Load failed: {e}")


@router.post("/stix/bundles", response_model=UpsertResult)
async def ingest_bundle(
    request: Request,
    bundle: Dict[str, Any] = Body(...),
    strict: bool = Query(True, description="Apply strict ADM validation")
):
    """
    Ingest a user-supplied STIX bundle.
    
    This endpoint accepts bundles generated by the mapper or manually created,
    validates them, and upserts to the graph and vector stores.
    """
    try:
        # Basic bundle validation
        if not bundle.get("type") == "bundle":
            raise ValueError("Invalid bundle: missing or wrong type")
        
        if "objects" not in bundle:
            raise ValueError("Invalid bundle: missing objects")
        
        # Create synthetic collection/version for user bundles
        bundle_id = bundle.get("id", f"bundle--{uuid.uuid4()}")
        collection = "user-supplied"
        version = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
        
        # Apply ADM validation
        ok, rejected, adm_sha = adm_validate(bundle, strict, settings.adm_mode, settings.adm_spec_min)
        
        if not ok and strict:
            return UpsertResult(
                inserted=0,
                updated=0,
                rejected=rejected,
                provenance=make_provenance(
                    collection=collection,
                    version=version,
                    modified=datetime.utcnow().isoformat(),
                    url=f"user:{bundle_id}",
                    adm_spec=settings.adm_spec_min,
                    adm_sha=adm_sha
                ),
                trace_id=getattr(request.state, 'trace_id', None)
            )
        
        # Upsert to graph and vectors
        inserted, updated = upsert_to_graph_and_vectors(
            bundle=bundle,
            collection=collection,
            version=version,
            neo4j_uri=settings.neo4j_uri,
            neo4j_user=settings.neo4j_user,
            neo4j_password=settings.neo4j_password,
            os_url=settings.opensearch_url,
            os_index=settings.os_index_nodes
        )
        
        return UpsertResult(
            inserted=inserted,
            updated=updated,
            rejected=rejected if rejected else [],
            provenance=make_provenance(
                collection=collection,
                version=version,
                modified=datetime.utcnow().isoformat(),
                url=f"user:{bundle_id}",
                adm_spec=settings.adm_spec_min if strict else None,
                adm_sha=adm_sha if strict else None
            ),
            trace_id=getattr(request.state, 'trace_id', None)
        )
        
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Bundle ingestion failed: {str(e)}")